### ISSUE TITLE
java.io.IOException: Server returned HTTP response code: 403 for URL: https://addons-ecs.forgesvc.net/api/v2/addon/306612/files

### ISSUE THREAD

**Issue by TheMrRedSlime** [ExtraCrafTX/GeneratorFabricMod#26] opened 2022-05-26 03:47 UTC
**Got a Error**

java.io.IOException: Server returned HTTP response code: 403 for URL: https://addons-ecs.forgesvc.net/api/v2/addon/306612/files
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at com.extracraftx.minecraft.templatemakerfabric.data.DataProvider.getUrl(DataProvider.java:278)
        at com.extracraftx.minecraft.templatemakerfabric.data.DataProvider.jsonFromUrl(DataProvider.java:273)
        at com.extracraftx.minecraft.templatemakerfabric.data.DataProvider.getFabricApiVersions(DataProvider.java:121)
        at com.extracraftx.minecraft.templatemakerfabric.data.DataProvider.getSortedFabricApiVersions(DataProvider.java:141)
        at com.extracraftx.minecraft.generatorfabricmod.GeneratorFabricMod.main(GeneratorFabricMod.java:66)

**Comment by ExtraCrafTX** [comment] 2022-05-26 09:38
Duplicate of #25, will push a fix soon.

**Closed as not planned by ExtraCrafTX** 2022-05-26 09:38 UTC

**Comment by partisani** [comment] 2022-06-30 00:49
I got a error code of 503

**Comment by ExtraCrafTX** [comment] 2022-07-01 14:41
> I got a error code of 503

This seems unrelated to this issue. Make sure you are using the latest version, if you still get this error please create a new issue with the version and logs.
